### ISSUE TITLE
Add mechanism to flag full text as incomplete

### ISSUE THREAD

**Issue by demiankatz** [demiankatz/Geeby-Deeby#59]
Useful for links to damaged copies, etc. Should also think about RDF representation, and whether we need to account for other statuses and/or notes.

**Comment by mshort** [comment]
Some properties that might be useful to have on Copy: has identifier for item, is bound with, has note on item, has owner agent, is reprinted as.

**Comment by demiankatz** [comment]
Resolved by #75.
